# Generated by Django 4.0.5 on 2022-12-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_class',
            name='subject',
        ),
        migrations.AddField(
            model_name='school_class',
            name='course',
            field=models.ManyToManyField(to='school_app.course'),
        ),
    ]
